#!/bin/bash

# update all demo sites with docker containers

tool="https://magestore-system:d42e15d72045fb5439465101912c64115f73f245@github.com/Magestore/omc-release-tool.git"

echo "----------------------------------"
name="starter-m1-01"
echo "${name}:"
m="m1"
n="01"
package="starter"
magento_root="/var/www/html"
docker exec -i $name sh -c "rm -rf omc-release-tool"
docker exec -i $name sh -c "git clone $tool omc-release-tool"
docker exec -i $name sh -c "cd omc-release-tool && rm -rf $magento_root/deploy && cp -r deploy-$m $magento_root/deploy"
docker exec -i $name sh -c "cd $magento_root/deploy && cat repo.list-$package > repo.list"
docker exec -i $name sh -c "cd $magento_root/deploy && bash run.sh"
docker exec -i $name sh -c "cd / && rm -rf omc-release-tool"
echo "Done"
echo ""
echo "----------------------------------"
name="growth-m1-01"
echo "${name}:"
m="m1"
n="01"
package="growth"
magento_root="/var/www/html"
docker exec -i $name sh -c "rm -rf omc-release-tool"
docker exec -i $name sh -c "git clone $tool omc-release-tool"
docker exec -i $name sh -c "cd omc-release-tool && rm -rf $magento_root/deploy && cp -r deploy-$m $magento_root/deploy"
docker exec -i $name sh -c "cd $magento_root/deploy && cat repo.list-$package > repo.list"
docker exec -i $name sh -c "cd $magento_root/deploy && bash run.sh"
docker exec -i $name sh -c "cd / && rm -rf omc-release-tool"
echo "Done"
echo ""
echo "----------------------------------"
name="growth-m1-02"
echo "${name}:"
m="m1"
n="02"
package="growth"
magento_root="/var/www/html"
docker exec -i $name sh -c "rm -rf omc-release-tool"
docker exec -i $name sh -c "git clone $tool omc-release-tool"
docker exec -i $name sh -c "cd omc-release-tool && rm -rf $magento_root/deploy && cp -r deploy-$m $magento_root/deploy"
docker exec -i $name sh -c "cd $magento_root/deploy && cat repo.list-$package > repo.list"
docker exec -i $name sh -c "cd $magento_root/deploy && bash run.sh"
docker exec -i $name sh -c "cd / && rm -rf omc-release-tool"
echo "Done"
echo ""
echo "----------------------------------"
name="starter-m2-03"
echo "${name}:"
m="m2"
n="03"
package="starter"
magento_root="/var/www/m2/starter/03"
docker exec -i $name sh -c "rm -rf omc-release-tool"
docker exec -i $name sh -c "git clone $tool omc-release-tool"
docker exec -i $name sh -c "cd omc-release-tool && rm -rf $magento_root/deploy && cp -r deploy-$m $magento_root/deploy"
docker exec -i $name sh -c "cd $magento_root/deploy && cat repo.list-$package > repo.list"
docker exec -i $name sh -c "cd $magento_root/deploy && bash run.sh"
docker exec -i $name sh -c "cd / && rm -rf omc-release-tool"
echo "Done"
echo ""
echo "----------------------------------"
name="growth-m2-01"
echo "${name}:"
m="m2"
n="01"
package="growth"
magento_root="/var/www/m2/growth/01"
docker exec -i $name sh -c "rm -rf omc-release-tool"
docker exec -i $name sh -c "git clone $tool omc-release-tool"
docker exec -i $name sh -c "cd omc-release-tool && rm -rf $magento_root/deploy && cp -r deploy-$m $magento_root/deploy"
docker exec -i $name sh -c "cd $magento_root/deploy && cat repo.list-$package > repo.list"
docker exec -i $name sh -c "cd $magento_root/deploy && bash run.sh"
docker exec -i $name sh -c "cd / && rm -rf omc-release-tool"
echo "Done"
echo ""
echo "----------------------------------"
name="growth-plus-m2-01"
echo "${name}:"
m="m2"
n="01"
package="plus"
magento_root="/var/www/m2/growth-plus/01"
docker exec -i $name sh -c "rm -rf omc-release-tool"
docker exec -i $name sh -c "git clone $tool omc-release-tool"
docker exec -i $name sh -c "cd omc-release-tool && rm -rf $magento_root/deploy && cp -r deploy-$m $magento_root/deploy"
docker exec -i $name sh -c "cd $magento_root/deploy && cat repo.list-$package > repo.list"
docker exec -i $name sh -c "cd $magento_root/deploy && bash run.sh"
docker exec -i $name sh -c "cd / && rm -rf omc-release-tool"
echo "Done"
echo ""
echo "----------------------------------"
name="growth-plus-m2-02"
echo "${name}:"
m="m2"
n="02"
package="plus"
magento_root="/var/www/m2/growth-plus/02"
docker exec -i $name sh -c "rm -rf omc-release-tool"
docker exec -i $name sh -c "git clone $tool omc-release-tool"
docker exec -i $name sh -c "cd omc-release-tool && rm -rf $magento_root/deploy && cp -r deploy-$m $magento_root/deploy"
docker exec -i $name sh -c "cd $magento_root/deploy && cat repo.list-$package > repo.list"
docker exec -i $name sh -c "cd $magento_root/deploy && bash run.sh"
docker exec -i $name sh -c "cd / && rm -rf omc-release-tool"
echo "Done"
echo ""
echo "----------------------------------"
name="growth-plus-m2-03"
echo "${name}:"
m="m2"
n="03"
package="plus"
magento_root="/var/www/m2/growth-plus/03"
docker exec -i $name sh -c "rm -rf omc-release-tool"
docker exec -i $name sh -c "git clone $tool omc-release-tool"
docker exec -i $name sh -c "cd omc-release-tool && rm -rf $magento_root/deploy && cp -r deploy-$m $magento_root/deploy"
docker exec -i $name sh -c "cd $magento_root/deploy && cat repo.list-$package > repo.list"
docker exec -i $name sh -c "cd $magento_root/deploy && bash run.sh"
docker exec -i $name sh -c "cd / && rm -rf omc-release-tool"
echo "Done"
echo ""
echo "----------------------------------"
name="growth-plus-m2-04"
echo "${name}:"
m="m2"
n="04"
package="plus"
magento_root="/var/www/m2/growth-plus/04"
docker exec -i $name sh -c "rm -rf omc-release-tool"
docker exec -i $name sh -c "git clone $tool omc-release-tool"
docker exec -i $name sh -c "cd omc-release-tool && rm -rf $magento_root/deploy && cp -r deploy-$m $magento_root/deploy"
docker exec -i $name sh -c "cd $magento_root/deploy && cat repo.list-$package > repo.list"
docker exec -i $name sh -c "cd $magento_root/deploy && bash run.sh"
docker exec -i $name sh -c "cd / && rm -rf omc-release-tool"
echo "Done"
echo ""
echo "----------------------------------"
name="growth-plus-m2-business"
echo "${name}:"
m="m2"
n="business"
package="plus"
magento_root="/var/www/m2/growth-plus/business"
docker exec -i $name sh -c "rm -rf omc-release-tool"
docker exec -i $name sh -c "git clone $tool omc-release-tool"
docker exec -i $name sh -c "cd omc-release-tool && rm -rf $magento_root/deploy && cp -r deploy-$m $magento_root/deploy"
docker exec -i $name sh -c "cd $magento_root/deploy && cat repo.list-$package > repo.list"
docker exec -i $name sh -c "cd $magento_root/deploy && bash run.sh"
docker exec -i $name sh -c "cd / && rm -rf omc-release-tool"
echo "Done"
echo ""
